/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdsenseRecord extends org.jooq.impl.UpdatableRecordImpl<info.blogstack.persistence.jooq.tables.records.AdsenseRecord> implements org.jooq.Record5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String>, info.blogstack.persistence.jooq.tables.interfaces.IAdsense {

	private static final long serialVersionUID = -1073928193;

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	@Override
	public void setAdsenseadclient(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	@Override
	public java.lang.String getAdsenseadclient() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	@Override
	public void setAdsenseslotbigrectangle(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	@Override
	public java.lang.String getAdsenseslotbigrectangle() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	@Override
	public void setAdsenseslotwideskycraper(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	@Override
	public java.lang.String getAdsenseslotwideskycraper() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	@Override
	public void setAdsenseslothorizontalskycraper(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	@Override
	public java.lang.String getAdsenseslothorizontalskycraper() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return info.blogstack.persistence.jooq.tables.Adsense.ADSENSE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return info.blogstack.persistence.jooq.tables.Adsense.ADSENSE.ADSENSEADCLIENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return info.blogstack.persistence.jooq.tables.Adsense.ADSENSE.ADSENSESLOTBIGRECTANGLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return info.blogstack.persistence.jooq.tables.Adsense.ADSENSE.ADSENSESLOTWIDESKYCRAPER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return info.blogstack.persistence.jooq.tables.Adsense.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAdsenseadclient();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAdsenseslotbigrectangle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAdsenseslotwideskycraper();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAdsenseslothorizontalskycraper();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value2(java.lang.String value) {
		setAdsenseadclient(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value3(java.lang.String value) {
		setAdsenseslotbigrectangle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value4(java.lang.String value) {
		setAdsenseslotwideskycraper(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value5(java.lang.String value) {
		setAdsenseslothorizontalskycraper(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IAdsense from) {
		setId(from.getId());
		setAdsenseadclient(from.getAdsenseadclient());
		setAdsenseslotbigrectangle(from.getAdsenseslotbigrectangle());
		setAdsenseslotwideskycraper(from.getAdsenseslotwideskycraper());
		setAdsenseslothorizontalskycraper(from.getAdsenseslothorizontalskycraper());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IAdsense> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AdsenseRecord
	 */
	public AdsenseRecord() {
		super(info.blogstack.persistence.jooq.tables.Adsense.ADSENSE);
	}

	/**
	 * Create a detached, initialised AdsenseRecord
	 */
	public AdsenseRecord(java.lang.Long id, java.lang.String adsenseadclient, java.lang.String adsenseslotbigrectangle, java.lang.String adsenseslotwideskycraper, java.lang.String adsenseslothorizontalskycraper) {
		super(info.blogstack.persistence.jooq.tables.Adsense.ADSENSE);

		setValue(0, id);
		setValue(1, adsenseadclient);
		setValue(2, adsenseslotbigrectangle);
		setValue(3, adsenseslotwideskycraper);
		setValue(4, adsenseslothorizontalskycraper);
	}
}
