/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.records;


import info.blogstack.persistence.jooq.tables.Adsense;
import info.blogstack.persistence.jooq.tables.interfaces.IAdsense;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdsenseRecord extends UpdatableRecordImpl<AdsenseRecord> implements Record5<Long, String, String, String, String>, IAdsense {

	private static final long serialVersionUID = 552164311;

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	@Override
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	@Override
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	@Override
	public void setAdsenseadclient(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	@Override
	public String getAdsenseadclient() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	@Override
	public void setAdsenseslotbigrectangle(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	@Override
	public String getAdsenseslotbigrectangle() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	@Override
	public void setAdsenseslotwideskycraper(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	@Override
	public String getAdsenseslotwideskycraper() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	@Override
	public void setAdsenseslothorizontalskycraper(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	@Override
	public String getAdsenseslothorizontalskycraper() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, String, String, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, String, String, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Adsense.ADSENSE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Adsense.ADSENSE.ADSENSEADCLIENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Adsense.ADSENSE.ADSENSESLOTBIGRECTANGLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Adsense.ADSENSE.ADSENSESLOTWIDESKYCRAPER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Adsense.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAdsenseadclient();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAdsenseslotbigrectangle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAdsenseslotwideskycraper();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAdsenseslothorizontalskycraper();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value2(String value) {
		setAdsenseadclient(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value3(String value) {
		setAdsenseslotbigrectangle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value4(String value) {
		setAdsenseslotwideskycraper(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord value5(String value) {
		setAdsenseslothorizontalskycraper(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsenseRecord values(Long value1, String value2, String value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IAdsense from) {
		setId(from.getId());
		setAdsenseadclient(from.getAdsenseadclient());
		setAdsenseslotbigrectangle(from.getAdsenseslotbigrectangle());
		setAdsenseslotwideskycraper(from.getAdsenseslotwideskycraper());
		setAdsenseslothorizontalskycraper(from.getAdsenseslothorizontalskycraper());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IAdsense> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AdsenseRecord
	 */
	public AdsenseRecord() {
		super(Adsense.ADSENSE);
	}

	/**
	 * Create a detached, initialised AdsenseRecord
	 */
	public AdsenseRecord(Long id, String adsenseadclient, String adsenseslotbigrectangle, String adsenseslotwideskycraper, String adsenseslothorizontalskycraper) {
		super(Adsense.ADSENSE);

		setValue(0, id);
		setValue(1, adsenseadclient);
		setValue(2, adsenseslotbigrectangle);
		setValue(3, adsenseslotwideskycraper);
		setValue(4, adsenseslothorizontalskycraper);
	}
}
