/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImportSourceRecord extends org.jooq.impl.UpdatableRecordImpl<info.blogstack.persistence.jooq.tables.records.ImportSourceRecord> implements org.jooq.Record3<java.lang.Long, org.joda.time.DateTime, org.joda.time.DateTime>, info.blogstack.persistence.jooq.tables.interfaces.IImportSource {

	private static final long serialVersionUID = -53868032;

	/**
	 * Setter for <code>BLOGSTACK.IMPORT_SOURCE.ID</code>.
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.IMPORT_SOURCE.ID</code>.
	 */
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>BLOGSTACK.IMPORT_SOURCE.CREATIONDATE</code>.
	 */
	@Override
	public void setCreationdate(org.joda.time.DateTime value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.IMPORT_SOURCE.CREATIONDATE</code>.
	 */
	@Override
	public org.joda.time.DateTime getCreationdate() {
		return (org.joda.time.DateTime) getValue(1);
	}

	/**
	 * Setter for <code>BLOGSTACK.IMPORT_SOURCE.UPDATEDATE</code>.
	 */
	@Override
	public void setUpdatedate(org.joda.time.DateTime value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.IMPORT_SOURCE.UPDATEDATE</code>.
	 */
	@Override
	public org.joda.time.DateTime getUpdatedate() {
		return (org.joda.time.DateTime) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, org.joda.time.DateTime, org.joda.time.DateTime> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, org.joda.time.DateTime, org.joda.time.DateTime> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return info.blogstack.persistence.jooq.tables.ImportSource.IMPORT_SOURCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field2() {
		return info.blogstack.persistence.jooq.tables.ImportSource.IMPORT_SOURCE.CREATIONDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field3() {
		return info.blogstack.persistence.jooq.tables.ImportSource.IMPORT_SOURCE.UPDATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value2() {
		return getCreationdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value3() {
		return getUpdatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportSourceRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportSourceRecord value2(org.joda.time.DateTime value) {
		setCreationdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportSourceRecord value3(org.joda.time.DateTime value) {
		setUpdatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportSourceRecord values(java.lang.Long value1, org.joda.time.DateTime value2, org.joda.time.DateTime value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IImportSource from) {
		setId(from.getId());
		setCreationdate(from.getCreationdate());
		setUpdatedate(from.getUpdatedate());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IImportSource> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ImportSourceRecord
	 */
	public ImportSourceRecord() {
		super(info.blogstack.persistence.jooq.tables.ImportSource.IMPORT_SOURCE);
	}

	/**
	 * Create a detached, initialised ImportSourceRecord
	 */
	public ImportSourceRecord(java.lang.Long id, org.joda.time.DateTime creationdate, org.joda.time.DateTime updatedate) {
		super(info.blogstack.persistence.jooq.tables.ImportSource.IMPORT_SOURCE);

		setValue(0, id);
		setValue(1, creationdate);
		setValue(2, updatedate);
	}
}
