/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndexationRecord extends org.jooq.impl.UpdatableRecordImpl<info.blogstack.persistence.jooq.tables.records.IndexationRecord> implements org.jooq.Record2<java.lang.Long, org.joda.time.DateTime>, info.blogstack.persistence.jooq.tables.interfaces.IIndexation {

	private static final long serialVersionUID = 725045832;

	/**
	 * Setter for <code>BLOGSTACK.INDEXATION.ID</code>.
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.INDEXATION.ID</code>.
	 */
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>BLOGSTACK.INDEXATION.CREATIONDATE</code>.
	 */
	@Override
	public void setCreationdate(org.joda.time.DateTime value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.INDEXATION.CREATIONDATE</code>.
	 */
	@Override
	public org.joda.time.DateTime getCreationdate() {
		return (org.joda.time.DateTime) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, org.joda.time.DateTime> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, org.joda.time.DateTime> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return info.blogstack.persistence.jooq.tables.Indexation.INDEXATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field2() {
		return info.blogstack.persistence.jooq.tables.Indexation.INDEXATION.CREATIONDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value2() {
		return getCreationdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndexationRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndexationRecord value2(org.joda.time.DateTime value) {
		setCreationdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IndexationRecord values(java.lang.Long value1, org.joda.time.DateTime value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IIndexation from) {
		setId(from.getId());
		setCreationdate(from.getCreationdate());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IIndexation> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IndexationRecord
	 */
	public IndexationRecord() {
		super(info.blogstack.persistence.jooq.tables.Indexation.INDEXATION);
	}

	/**
	 * Create a detached, initialised IndexationRecord
	 */
	public IndexationRecord(java.lang.Long id, org.joda.time.DateTime creationdate) {
		super(info.blogstack.persistence.jooq.tables.Indexation.INDEXATION);

		setValue(0, id);
		setValue(1, creationdate);
	}
}
