/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabelRecord extends org.jooq.impl.UpdatableRecordImpl<info.blogstack.persistence.jooq.tables.records.LabelRecord> implements org.jooq.Record6<java.lang.Long, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean>, info.blogstack.persistence.jooq.tables.interfaces.ILabel {

	private static final long serialVersionUID = 1446768048;

	/**
	 * Setter for <code>BLOGSTACK.LABEL.ID</code>.
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.LABEL.ID</code>.
	 */
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>BLOGSTACK.LABEL.CREATIONDATE</code>.
	 */
	@Override
	public void setCreationdate(org.joda.time.DateTime value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.LABEL.CREATIONDATE</code>.
	 */
	@Override
	public org.joda.time.DateTime getCreationdate() {
		return (org.joda.time.DateTime) getValue(1);
	}

	/**
	 * Setter for <code>BLOGSTACK.LABEL.NAME</code>.
	 */
	@Override
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.LABEL.NAME</code>.
	 */
	@Override
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>BLOGSTACK.LABEL.HASH</code>.
	 */
	@Override
	public void setHash(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.LABEL.HASH</code>.
	 */
	@Override
	public java.lang.String getHash() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>BLOGSTACK.LABEL.ENABLED</code>.
	 */
	@Override
	public void setEnabled(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.LABEL.ENABLED</code>.
	 */
	@Override
	public java.lang.Boolean getEnabled() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>BLOGSTACK.LABEL.VISIBLE</code>.
	 */
	@Override
	public void setVisible(java.lang.Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.LABEL.VISIBLE</code>.
	 */
	@Override
	public java.lang.Boolean getVisible() {
		return (java.lang.Boolean) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return info.blogstack.persistence.jooq.tables.Label.LABEL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field2() {
		return info.blogstack.persistence.jooq.tables.Label.LABEL.CREATIONDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return info.blogstack.persistence.jooq.tables.Label.LABEL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return info.blogstack.persistence.jooq.tables.Label.LABEL.HASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return info.blogstack.persistence.jooq.tables.Label.LABEL.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field6() {
		return info.blogstack.persistence.jooq.tables.Label.LABEL.VISIBLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value2() {
		return getCreationdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getHash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value6() {
		return getVisible();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value2(org.joda.time.DateTime value) {
		setCreationdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value4(java.lang.String value) {
		setHash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value5(java.lang.Boolean value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value6(java.lang.Boolean value) {
		setVisible(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord values(java.lang.Long value1, org.joda.time.DateTime value2, java.lang.String value3, java.lang.String value4, java.lang.Boolean value5, java.lang.Boolean value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(info.blogstack.persistence.jooq.tables.interfaces.ILabel from) {
		setId(from.getId());
		setCreationdate(from.getCreationdate());
		setName(from.getName());
		setHash(from.getHash());
		setEnabled(from.getEnabled());
		setVisible(from.getVisible());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.ILabel> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LabelRecord
	 */
	public LabelRecord() {
		super(info.blogstack.persistence.jooq.tables.Label.LABEL);
	}

	/**
	 * Create a detached, initialised LabelRecord
	 */
	public LabelRecord(java.lang.Long id, org.joda.time.DateTime creationdate, java.lang.String name, java.lang.String hash, java.lang.Boolean enabled, java.lang.Boolean visible) {
		super(info.blogstack.persistence.jooq.tables.Label.LABEL);

		setValue(0, id);
		setValue(1, creationdate);
		setValue(2, name);
		setValue(3, hash);
		setValue(4, enabled);
		setValue(5, visible);
	}
}
