/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostsIndexationsRecord extends org.jooq.impl.UpdatableRecordImpl<info.blogstack.persistence.jooq.tables.records.PostsIndexationsRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.Long>, info.blogstack.persistence.jooq.tables.interfaces.IPostsIndexations {

	private static final long serialVersionUID = -1502396524;

	/**
	 * Setter for <code>BLOGSTACK.POSTS_INDEXATIONS.ID</code>.
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.POSTS_INDEXATIONS.ID</code>.
	 */
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>BLOGSTACK.POSTS_INDEXATIONS.POST_ID</code>.
	 */
	@Override
	public void setPostId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.POSTS_INDEXATIONS.POST_ID</code>.
	 */
	@Override
	public java.lang.Long getPostId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>BLOGSTACK.POSTS_INDEXATIONS.INDEXATION_ID</code>.
	 */
	@Override
	public void setIndexationId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.POSTS_INDEXATIONS.INDEXATION_ID</code>.
	 */
	@Override
	public java.lang.Long getIndexationId() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return info.blogstack.persistence.jooq.tables.PostsIndexations.POSTS_INDEXATIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return info.blogstack.persistence.jooq.tables.PostsIndexations.POSTS_INDEXATIONS.POST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return info.blogstack.persistence.jooq.tables.PostsIndexations.POSTS_INDEXATIONS.INDEXATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getPostId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getIndexationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsIndexationsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsIndexationsRecord value2(java.lang.Long value) {
		setPostId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsIndexationsRecord value3(java.lang.Long value) {
		setIndexationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsIndexationsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IPostsIndexations from) {
		setId(from.getId());
		setPostId(from.getPostId());
		setIndexationId(from.getIndexationId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IPostsIndexations> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PostsIndexationsRecord
	 */
	public PostsIndexationsRecord() {
		super(info.blogstack.persistence.jooq.tables.PostsIndexations.POSTS_INDEXATIONS);
	}

	/**
	 * Create a detached, initialised PostsIndexationsRecord
	 */
	public PostsIndexationsRecord(java.lang.Long id, java.lang.Long postId, java.lang.Long indexationId) {
		super(info.blogstack.persistence.jooq.tables.PostsIndexations.POSTS_INDEXATIONS);

		setValue(0, id);
		setValue(1, postId);
		setValue(2, indexationId);
	}
}
