/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceRecord extends org.jooq.impl.UpdatableRecordImpl<info.blogstack.persistence.jooq.tables.records.SourceRecord> implements org.jooq.Record13<java.lang.Long, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Boolean>, info.blogstack.persistence.jooq.tables.interfaces.ISource {

	private static final long serialVersionUID = 58397760;

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ID</code>.
	 */
	@Override
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ID</code>.
	 */
	@Override
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.CREATIONDATE</code>.
	 */
	@Override
	public void setCreationdate(org.joda.time.DateTime value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.CREATIONDATE</code>.
	 */
	@Override
	public org.joda.time.DateTime getCreationdate() {
		return (org.joda.time.DateTime) getValue(1);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.UPDATEDATE</code>.
	 */
	@Override
	public void setUpdatedate(org.joda.time.DateTime value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.UPDATEDATE</code>.
	 */
	@Override
	public org.joda.time.DateTime getUpdatedate() {
		return (org.joda.time.DateTime) getValue(2);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.NAME</code>.
	 */
	@Override
	public void setName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.NAME</code>.
	 */
	@Override
	public java.lang.String getName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ALIAS</code>.
	 */
	@Override
	public void setAlias(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ALIAS</code>.
	 */
	@Override
	public java.lang.String getAlias() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.PAGEURL</code>.
	 */
	@Override
	public void setPageurl(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.PAGEURL</code>.
	 */
	@Override
	public java.lang.String getPageurl() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.URL</code>.
	 */
	@Override
	public void setUrl(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.URL</code>.
	 */
	@Override
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.AUTHOR</code>.
	 */
	@Override
	public void setAuthor(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.AUTHOR</code>.
	 */
	@Override
	public java.lang.String getAuthor() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.EMAIL</code>.
	 */
	@Override
	public void setEmail(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.EMAIL</code>.
	 */
	@Override
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.DISQUSSHORTNAME</code>.
	 */
	@Override
	public void setDisqusshortname(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.DISQUSSHORTNAME</code>.
	 */
	@Override
	public java.lang.String getDisqusshortname() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ADSENSE_ID</code>.
	 */
	@Override
	public void setAdsenseId(java.lang.Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ADSENSE_ID</code>.
	 */
	@Override
	public java.lang.Long getAdsenseId() {
		return (java.lang.Long) getValue(10);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.IMPORTSOURCE_ID</code>.
	 */
	@Override
	public void setImportsourceId(java.lang.Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.IMPORTSOURCE_ID</code>.
	 */
	@Override
	public java.lang.Long getImportsourceId() {
		return (java.lang.Long) getValue(11);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ENABLED</code>.
	 */
	@Override
	public void setEnabled(java.lang.Boolean value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ENABLED</code>.
	 */
	@Override
	public java.lang.Boolean getEnabled() {
		return (java.lang.Boolean) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Long, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Long, org.joda.time.DateTime, org.joda.time.DateTime, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field2() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.CREATIONDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field3() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.UPDATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.ALIAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.PAGEURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.DISQUSSHORTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field11() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.ADSENSE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field12() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.IMPORTSOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field13() {
		return info.blogstack.persistence.jooq.tables.Source.SOURCE.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value2() {
		return getCreationdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value3() {
		return getUpdatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAlias();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getPageurl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getDisqusshortname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value11() {
		return getAdsenseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value12() {
		return getImportsourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value13() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value2(org.joda.time.DateTime value) {
		setCreationdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value3(org.joda.time.DateTime value) {
		setUpdatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value4(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value5(java.lang.String value) {
		setAlias(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value6(java.lang.String value) {
		setPageurl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value7(java.lang.String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value8(java.lang.String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value9(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value10(java.lang.String value) {
		setDisqusshortname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value11(java.lang.Long value) {
		setAdsenseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value12(java.lang.Long value) {
		setImportsourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value13(java.lang.Boolean value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord values(java.lang.Long value1, org.joda.time.DateTime value2, org.joda.time.DateTime value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.Long value11, java.lang.Long value12, java.lang.Boolean value13) {
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(info.blogstack.persistence.jooq.tables.interfaces.ISource from) {
		setId(from.getId());
		setCreationdate(from.getCreationdate());
		setUpdatedate(from.getUpdatedate());
		setName(from.getName());
		setAlias(from.getAlias());
		setPageurl(from.getPageurl());
		setUrl(from.getUrl());
		setAuthor(from.getAuthor());
		setEmail(from.getEmail());
		setDisqusshortname(from.getDisqusshortname());
		setAdsenseId(from.getAdsenseId());
		setImportsourceId(from.getImportsourceId());
		setEnabled(from.getEnabled());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.ISource> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SourceRecord
	 */
	public SourceRecord() {
		super(info.blogstack.persistence.jooq.tables.Source.SOURCE);
	}

	/**
	 * Create a detached, initialised SourceRecord
	 */
	public SourceRecord(java.lang.Long id, org.joda.time.DateTime creationdate, org.joda.time.DateTime updatedate, java.lang.String name, java.lang.String alias, java.lang.String pageurl, java.lang.String url, java.lang.String author, java.lang.String email, java.lang.String disqusshortname, java.lang.Long adsenseId, java.lang.Long importsourceId, java.lang.Boolean enabled) {
		super(info.blogstack.persistence.jooq.tables.Source.SOURCE);

		setValue(0, id);
		setValue(1, creationdate);
		setValue(2, updatedate);
		setValue(3, name);
		setValue(4, alias);
		setValue(5, pageurl);
		setValue(6, url);
		setValue(7, author);
		setValue(8, email);
		setValue(9, disqusshortname);
		setValue(10, adsenseId);
		setValue(11, importsourceId);
		setValue(12, enabled);
	}
}
