/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.records;


import info.blogstack.persistence.jooq.tables.Source;
import info.blogstack.persistence.jooq.tables.interfaces.ISource;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceRecord extends UpdatableRecordImpl<SourceRecord> implements Record13<Long, DateTime, DateTime, String, String, String, String, String, String, String, Long, Long, Boolean>, ISource {

	private static final long serialVersionUID = 2108027676;

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ID</code>.
	 */
	@Override
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ID</code>.
	 */
	@Override
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.CREATIONDATE</code>.
	 */
	@Override
	public void setCreationdate(DateTime value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.CREATIONDATE</code>.
	 */
	@Override
	public DateTime getCreationdate() {
		return (DateTime) getValue(1);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.UPDATEDATE</code>.
	 */
	@Override
	public void setUpdatedate(DateTime value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.UPDATEDATE</code>.
	 */
	@Override
	public DateTime getUpdatedate() {
		return (DateTime) getValue(2);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.NAME</code>.
	 */
	@Override
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.NAME</code>.
	 */
	@Override
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ALIAS</code>.
	 */
	@Override
	public void setAlias(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ALIAS</code>.
	 */
	@Override
	public String getAlias() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.PAGEURL</code>.
	 */
	@Override
	public void setPageurl(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.PAGEURL</code>.
	 */
	@Override
	public String getPageurl() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.URL</code>.
	 */
	@Override
	public void setUrl(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.URL</code>.
	 */
	@Override
	public String getUrl() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.AUTHOR</code>.
	 */
	@Override
	public void setAuthor(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.AUTHOR</code>.
	 */
	@Override
	public String getAuthor() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.EMAIL</code>.
	 */
	@Override
	public void setEmail(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.EMAIL</code>.
	 */
	@Override
	public String getEmail() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.DISQUSSHORTNAME</code>.
	 */
	@Override
	public void setDisqusshortname(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.DISQUSSHORTNAME</code>.
	 */
	@Override
	public String getDisqusshortname() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ADSENSE_ID</code>.
	 */
	@Override
	public void setAdsenseId(Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ADSENSE_ID</code>.
	 */
	@Override
	public Long getAdsenseId() {
		return (Long) getValue(10);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.IMPORTSOURCE_ID</code>.
	 */
	@Override
	public void setImportsourceId(Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.IMPORTSOURCE_ID</code>.
	 */
	@Override
	public Long getImportsourceId() {
		return (Long) getValue(11);
	}

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ENABLED</code>.
	 */
	@Override
	public void setEnabled(Boolean value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ENABLED</code>.
	 */
	@Override
	public Boolean getEnabled() {
		return (Boolean) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Long, DateTime, DateTime, String, String, String, String, String, String, String, Long, Long, Boolean> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Long, DateTime, DateTime, String, String, String, String, String, String, String, Long, Long, Boolean> valuesRow() {
		return (Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Source.SOURCE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<DateTime> field2() {
		return Source.SOURCE.CREATIONDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<DateTime> field3() {
		return Source.SOURCE.UPDATEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Source.SOURCE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Source.SOURCE.ALIAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Source.SOURCE.PAGEURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Source.SOURCE.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Source.SOURCE.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Source.SOURCE.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Source.SOURCE.DISQUSSHORTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field11() {
		return Source.SOURCE.ADSENSE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field12() {
		return Source.SOURCE.IMPORTSOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field13() {
		return Source.SOURCE.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DateTime value2() {
		return getCreationdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DateTime value3() {
		return getUpdatedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAlias();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getPageurl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getDisqusshortname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value11() {
		return getAdsenseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value12() {
		return getImportsourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value13() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value2(DateTime value) {
		setCreationdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value3(DateTime value) {
		setUpdatedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value5(String value) {
		setAlias(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value6(String value) {
		setPageurl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value7(String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value8(String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value9(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value10(String value) {
		setDisqusshortname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value11(Long value) {
		setAdsenseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value12(Long value) {
		setImportsourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord value13(Boolean value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SourceRecord values(Long value1, DateTime value2, DateTime value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Long value11, Long value12, Boolean value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ISource from) {
		setId(from.getId());
		setCreationdate(from.getCreationdate());
		setUpdatedate(from.getUpdatedate());
		setName(from.getName());
		setAlias(from.getAlias());
		setPageurl(from.getPageurl());
		setUrl(from.getUrl());
		setAuthor(from.getAuthor());
		setEmail(from.getEmail());
		setDisqusshortname(from.getDisqusshortname());
		setAdsenseId(from.getAdsenseId());
		setImportsourceId(from.getImportsourceId());
		setEnabled(from.getEnabled());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ISource> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SourceRecord
	 */
	public SourceRecord() {
		super(Source.SOURCE);
	}

	/**
	 * Create a detached, initialised SourceRecord
	 */
	public SourceRecord(Long id, DateTime creationdate, DateTime updatedate, String name, String alias, String pageurl, String url, String author, String email, String disqusshortname, Long adsenseId, Long importsourceId, Boolean enabled) {
		super(Source.SOURCE);

		setValue(0, id);
		setValue(1, creationdate);
		setValue(2, updatedate);
		setValue(3, name);
		setValue(4, alias);
		setValue(5, pageurl);
		setValue(6, url);
		setValue(7, author);
		setValue(8, email);
		setValue(9, disqusshortname);
		setValue(10, adsenseId);
		setValue(11, importsourceId);
		setValue(12, enabled);
	}
}
