/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAdsense extends Serializable {

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	public Long getId();

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	public void setAdsenseadclient(String value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	public String getAdsenseadclient();

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	public void setAdsenseslotbigrectangle(String value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	public String getAdsenseslotbigrectangle();

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	public void setAdsenseslotwideskycraper(String value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	public String getAdsenseslotwideskycraper();

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	public void setAdsenseslothorizontalskycraper(String value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	public String getAdsenseslothorizontalskycraper();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IAdsense
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IAdsense from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IAdsense
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IAdsense> E into(E into);
}
