/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAdsense extends java.io.Serializable {

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	public void setId(java.lang.Long value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	public java.lang.Long getId();

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	public void setAdsenseadclient(java.lang.String value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	public java.lang.String getAdsenseadclient();

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	public void setAdsenseslotbigrectangle(java.lang.String value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	public java.lang.String getAdsenseslotbigrectangle();

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	public void setAdsenseslotwideskycraper(java.lang.String value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	public java.lang.String getAdsenseslotwideskycraper();

	/**
	 * Setter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	public void setAdsenseslothorizontalskycraper(java.lang.String value);

	/**
	 * Getter for <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	public java.lang.String getAdsenseslothorizontalskycraper();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IAdsense
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IAdsense from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IAdsense
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IAdsense> E into(E into);
}
