/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IImportSource extends Serializable {

	/**
	 * Setter for <code>BLOGSTACK.IMPORT_SOURCE.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.IMPORT_SOURCE.ID</code>.
	 */
	public Long getId();

	/**
	 * Setter for <code>BLOGSTACK.IMPORT_SOURCE.CREATIONDATE</code>.
	 */
	public void setCreationdate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.IMPORT_SOURCE.CREATIONDATE</code>.
	 */
	public DateTime getCreationdate();

	/**
	 * Setter for <code>BLOGSTACK.IMPORT_SOURCE.UPDATEDATE</code>.
	 */
	public void setUpdatedate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.IMPORT_SOURCE.UPDATEDATE</code>.
	 */
	public DateTime getUpdatedate();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IImportSource
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IImportSource from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IImportSource
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IImportSource> E into(E into);
}
