/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IIndexation extends Serializable {

	/**
	 * Setter for <code>BLOGSTACK.INDEXATION.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.INDEXATION.ID</code>.
	 */
	public Long getId();

	/**
	 * Setter for <code>BLOGSTACK.INDEXATION.CREATIONDATE</code>.
	 */
	public void setCreationdate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.INDEXATION.CREATIONDATE</code>.
	 */
	public DateTime getCreationdate();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IIndexation
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IIndexation from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IIndexation
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IIndexation> E into(E into);
}
