/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILabel extends Serializable {

	/**
	 * Setter for <code>BLOGSTACK.LABEL.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.LABEL.ID</code>.
	 */
	public Long getId();

	/**
	 * Setter for <code>BLOGSTACK.LABEL.CREATIONDATE</code>.
	 */
	public void setCreationdate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.LABEL.CREATIONDATE</code>.
	 */
	public DateTime getCreationdate();

	/**
	 * Setter for <code>BLOGSTACK.LABEL.NAME</code>.
	 */
	public void setName(String value);

	/**
	 * Getter for <code>BLOGSTACK.LABEL.NAME</code>.
	 */
	public String getName();

	/**
	 * Setter for <code>BLOGSTACK.LABEL.HASH</code>.
	 */
	public void setHash(String value);

	/**
	 * Getter for <code>BLOGSTACK.LABEL.HASH</code>.
	 */
	public String getHash();

	/**
	 * Setter for <code>BLOGSTACK.LABEL.ENABLED</code>.
	 */
	public void setEnabled(Boolean value);

	/**
	 * Getter for <code>BLOGSTACK.LABEL.ENABLED</code>.
	 */
	public Boolean getEnabled();

	/**
	 * Setter for <code>BLOGSTACK.LABEL.VISIBLE</code>.
	 */
	public void setVisible(Boolean value);

	/**
	 * Getter for <code>BLOGSTACK.LABEL.VISIBLE</code>.
	 */
	public Boolean getVisible();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ILabel
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.ILabel from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ILabel
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.ILabel> E into(E into);
}
