/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPostsLabels extends Serializable {

	/**
	 * Setter for <code>BLOGSTACK.POSTS_LABELS.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.POSTS_LABELS.ID</code>.
	 */
	public Long getId();

	/**
	 * Setter for <code>BLOGSTACK.POSTS_LABELS.POST_ID</code>.
	 */
	public void setPostId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.POSTS_LABELS.POST_ID</code>.
	 */
	public Long getPostId();

	/**
	 * Setter for <code>BLOGSTACK.POSTS_LABELS.LABEL_ID</code>.
	 */
	public void setLabelId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.POSTS_LABELS.LABEL_ID</code>.
	 */
	public Long getLabelId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IPostsLabels
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IPostsLabels from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IPostsLabels
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IPostsLabels> E into(E into);
}
