/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPost extends java.io.Serializable {

	/**
	 * Setter for <code>BLOGSTACK.POST.ID</code>.
	 */
	public void setId(java.lang.Long value);

	/**
	 * Getter for <code>BLOGSTACK.POST.ID</code>.
	 */
	public java.lang.Long getId();

	/**
	 * Setter for <code>BLOGSTACK.POST.CREATIONDATE</code>.
	 */
	public void setCreationdate(org.joda.time.DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.POST.CREATIONDATE</code>.
	 */
	public org.joda.time.DateTime getCreationdate();

	/**
	 * Setter for <code>BLOGSTACK.POST.UPDATEDATE</code>.
	 */
	public void setUpdatedate(org.joda.time.DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.POST.UPDATEDATE</code>.
	 */
	public org.joda.time.DateTime getUpdatedate();

	/**
	 * Setter for <code>BLOGSTACK.POST.PUBLISHDATE</code>.
	 */
	public void setPublishdate(org.joda.time.DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.POST.PUBLISHDATE</code>.
	 */
	public org.joda.time.DateTime getPublishdate();

	/**
	 * Setter for <code>BLOGSTACK.POST.DATE</code>.
	 */
	public void setDate(org.joda.time.DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.POST.DATE</code>.
	 */
	public org.joda.time.DateTime getDate();

	/**
	 * Setter for <code>BLOGSTACK.POST.URL</code>.
	 */
	public void setUrl(java.lang.String value);

	/**
	 * Getter for <code>BLOGSTACK.POST.URL</code>.
	 */
	public java.lang.String getUrl();

	/**
	 * Setter for <code>BLOGSTACK.POST.HASH</code>.
	 */
	public void setHash(java.lang.String value);

	/**
	 * Getter for <code>BLOGSTACK.POST.HASH</code>.
	 */
	public java.lang.String getHash();

	/**
	 * Setter for <code>BLOGSTACK.POST.TITLE</code>.
	 */
	public void setTitle(java.lang.String value);

	/**
	 * Getter for <code>BLOGSTACK.POST.TITLE</code>.
	 */
	public java.lang.String getTitle();

	/**
	 * Setter for <code>BLOGSTACK.POST.AUTHOR</code>.
	 */
	public void setAuthor(java.lang.String value);

	/**
	 * Getter for <code>BLOGSTACK.POST.AUTHOR</code>.
	 */
	public java.lang.String getAuthor();

	/**
	 * Setter for <code>BLOGSTACK.POST.CONTENTCOMPRESSED</code>.
	 */
	public void setContentcompressed(byte[] value);

	/**
	 * Getter for <code>BLOGSTACK.POST.CONTENTCOMPRESSED</code>.
	 */
	public byte[] getContentcompressed();

	/**
	 * Setter for <code>BLOGSTACK.POST.INDEXATION_ID</code>.
	 */
	public void setIndexationId(java.lang.Long value);

	/**
	 * Getter for <code>BLOGSTACK.POST.INDEXATION_ID</code>.
	 */
	public java.lang.Long getIndexationId();

	/**
	 * Setter for <code>BLOGSTACK.POST.SOURCE_ID</code>.
	 */
	public void setSourceId(java.lang.Long value);

	/**
	 * Getter for <code>BLOGSTACK.POST.SOURCE_ID</code>.
	 */
	public java.lang.Long getSourceId();

	/**
	 * Setter for <code>BLOGSTACK.POST.VISIBLE</code>.
	 */
	public void setVisible(java.lang.Boolean value);

	/**
	 * Getter for <code>BLOGSTACK.POST.VISIBLE</code>.
	 */
	public java.lang.Boolean getVisible();

	/**
	 * Setter for <code>BLOGSTACK.POST.SHARED</code>.
	 */
	public void setShared(java.lang.Boolean value);

	/**
	 * Getter for <code>BLOGSTACK.POST.SHARED</code>.
	 */
	public java.lang.Boolean getShared();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IPost
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IPost from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IPost
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IPost> E into(E into);
}
