/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPost extends Serializable {

	/**
	 * Setter for <code>BLOGSTACK.POST.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.POST.ID</code>.
	 */
	public Long getId();

	/**
	 * Setter for <code>BLOGSTACK.POST.CREATIONDATE</code>.
	 */
	public void setCreationdate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.POST.CREATIONDATE</code>.
	 */
	public DateTime getCreationdate();

	/**
	 * Setter for <code>BLOGSTACK.POST.UPDATEDATE</code>.
	 */
	public void setUpdatedate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.POST.UPDATEDATE</code>.
	 */
	public DateTime getUpdatedate();

	/**
	 * Setter for <code>BLOGSTACK.POST.PUBLISHDATE</code>.
	 */
	public void setPublishdate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.POST.PUBLISHDATE</code>.
	 */
	public DateTime getPublishdate();

	/**
	 * Setter for <code>BLOGSTACK.POST.DATE</code>.
	 */
	public void setDate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.POST.DATE</code>.
	 */
	public DateTime getDate();

	/**
	 * Setter for <code>BLOGSTACK.POST.URL</code>.
	 */
	public void setUrl(String value);

	/**
	 * Getter for <code>BLOGSTACK.POST.URL</code>.
	 */
	public String getUrl();

	/**
	 * Setter for <code>BLOGSTACK.POST.HASH</code>.
	 */
	public void setHash(String value);

	/**
	 * Getter for <code>BLOGSTACK.POST.HASH</code>.
	 */
	public String getHash();

	/**
	 * Setter for <code>BLOGSTACK.POST.TITLE</code>.
	 */
	public void setTitle(String value);

	/**
	 * Getter for <code>BLOGSTACK.POST.TITLE</code>.
	 */
	public String getTitle();

	/**
	 * Setter for <code>BLOGSTACK.POST.AUTHOR</code>.
	 */
	public void setAuthor(String value);

	/**
	 * Getter for <code>BLOGSTACK.POST.AUTHOR</code>.
	 */
	public String getAuthor();

	/**
	 * Setter for <code>BLOGSTACK.POST.CONTENTCOMPRESSED</code>.
	 */
	public void setContentcompressed(byte[] value);

	/**
	 * Getter for <code>BLOGSTACK.POST.CONTENTCOMPRESSED</code>.
	 */
	public byte[] getContentcompressed();

	/**
	 * Setter for <code>BLOGSTACK.POST.INDEXATION_ID</code>.
	 */
	public void setIndexationId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.POST.INDEXATION_ID</code>.
	 */
	public Long getIndexationId();

	/**
	 * Setter for <code>BLOGSTACK.POST.SOURCE_ID</code>.
	 */
	public void setSourceId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.POST.SOURCE_ID</code>.
	 */
	public Long getSourceId();

	/**
	 * Setter for <code>BLOGSTACK.POST.VISIBLE</code>.
	 */
	public void setVisible(Boolean value);

	/**
	 * Getter for <code>BLOGSTACK.POST.VISIBLE</code>.
	 */
	public Boolean getVisible();

	/**
	 * Setter for <code>BLOGSTACK.POST.SHARED</code>.
	 */
	public void setShared(Boolean value);

	/**
	 * Getter for <code>BLOGSTACK.POST.SHARED</code>.
	 */
	public Boolean getShared();

	/**
	 * Setter for <code>BLOGSTACK.POST.NEWSLETTER_ID</code>.
	 */
	public void setNewsletterId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.POST.NEWSLETTER_ID</code>.
	 */
	public Long getNewsletterId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IPost
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.IPost from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IPost
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.IPost> E into(E into);
}
