/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISource extends Serializable {

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ID</code>.
	 */
	public Long getId();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.CREATIONDATE</code>.
	 */
	public void setCreationdate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.CREATIONDATE</code>.
	 */
	public DateTime getCreationdate();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.UPDATEDATE</code>.
	 */
	public void setUpdatedate(DateTime value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.UPDATEDATE</code>.
	 */
	public DateTime getUpdatedate();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.NAME</code>.
	 */
	public void setName(String value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.NAME</code>.
	 */
	public String getName();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ALIAS</code>.
	 */
	public void setAlias(String value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ALIAS</code>.
	 */
	public String getAlias();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.PAGEURL</code>.
	 */
	public void setPageurl(String value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.PAGEURL</code>.
	 */
	public String getPageurl();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.URL</code>.
	 */
	public void setUrl(String value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.URL</code>.
	 */
	public String getUrl();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.AUTHOR</code>.
	 */
	public void setAuthor(String value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.AUTHOR</code>.
	 */
	public String getAuthor();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.EMAIL</code>.
	 */
	public void setEmail(String value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.EMAIL</code>.
	 */
	public String getEmail();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.DISQUSSHORTNAME</code>.
	 */
	public void setDisqusshortname(String value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.DISQUSSHORTNAME</code>.
	 */
	public String getDisqusshortname();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ADSENSE_ID</code>.
	 */
	public void setAdsenseId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ADSENSE_ID</code>.
	 */
	public Long getAdsenseId();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.IMPORTSOURCE_ID</code>.
	 */
	public void setImportsourceId(Long value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.IMPORTSOURCE_ID</code>.
	 */
	public Long getImportsourceId();

	/**
	 * Setter for <code>BLOGSTACK.SOURCE.ENABLED</code>.
	 */
	public void setEnabled(Boolean value);

	/**
	 * Getter for <code>BLOGSTACK.SOURCE.ENABLED</code>.
	 */
	public Boolean getEnabled();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ISource
	 */
	public void from(info.blogstack.persistence.jooq.tables.interfaces.ISource from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ISource
	 */
	public <E extends info.blogstack.persistence.jooq.tables.interfaces.ISource> E into(E into);
}
