/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adsense extends org.jooq.impl.TableImpl<info.blogstack.persistence.jooq.tables.records.AdsenseRecord> {

	private static final long serialVersionUID = 1736247659;

	/**
	 * The reference instance of <code>BLOGSTACK.ADSENSE</code>
	 */
	public static final info.blogstack.persistence.jooq.tables.Adsense ADSENSE = new info.blogstack.persistence.jooq.tables.Adsense();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<info.blogstack.persistence.jooq.tables.records.AdsenseRecord> getRecordType() {
		return info.blogstack.persistence.jooq.tables.records.AdsenseRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.AdsenseRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.AdsenseRecord, java.lang.String> ADSENSEADCLIENT = createField("ADSENSEADCLIENT", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.AdsenseRecord, java.lang.String> ADSENSESLOTBIGRECTANGLE = createField("ADSENSESLOTBIGRECTANGLE", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.AdsenseRecord, java.lang.String> ADSENSESLOTWIDESKYCRAPER = createField("ADSENSESLOTWIDESKYCRAPER", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.AdsenseRecord, java.lang.String> ADSENSESLOTHORIZONTALSKYCRAPER = createField("ADSENSESLOTHORIZONTALSKYCRAPER", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * Create a <code>BLOGSTACK.ADSENSE</code> table reference
	 */
	public Adsense() {
		this("ADSENSE", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.ADSENSE</code> table reference
	 */
	public Adsense(java.lang.String alias) {
		this(alias, info.blogstack.persistence.jooq.tables.Adsense.ADSENSE);
	}

	private Adsense(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.AdsenseRecord> aliased) {
		this(alias, aliased, null);
	}

	private Adsense(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.AdsenseRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, info.blogstack.persistence.jooq.Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<info.blogstack.persistence.jooq.tables.records.AdsenseRecord, java.lang.Long> getIdentity() {
		return info.blogstack.persistence.jooq.Keys.IDENTITY_ADSENSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.AdsenseRecord> getPrimaryKey() {
		return info.blogstack.persistence.jooq.Keys.PK_ADSENSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.AdsenseRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.AdsenseRecord>>asList(info.blogstack.persistence.jooq.Keys.PK_ADSENSE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public info.blogstack.persistence.jooq.tables.Adsense as(java.lang.String alias) {
		return new info.blogstack.persistence.jooq.tables.Adsense(alias, this);
	}

	/**
	 * Rename this table
	 */
	public info.blogstack.persistence.jooq.tables.Adsense rename(java.lang.String name) {
		return new info.blogstack.persistence.jooq.tables.Adsense(name, null);
	}
}
