/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;


import info.blogstack.persistence.jooq.Blogstack;
import info.blogstack.persistence.jooq.Keys;
import info.blogstack.persistence.jooq.tables.records.AdsenseRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adsense extends TableImpl<AdsenseRecord> {

	private static final long serialVersionUID = -724867077;

	/**
	 * The reference instance of <code>BLOGSTACK.ADSENSE</code>
	 */
	public static final Adsense ADSENSE = new Adsense();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AdsenseRecord> getRecordType() {
		return AdsenseRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ID</code>.
	 */
	public final TableField<AdsenseRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ADSENSEADCLIENT</code>.
	 */
	public final TableField<AdsenseRecord, String> ADSENSEADCLIENT = createField("ADSENSEADCLIENT", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ADSENSESLOTBIGRECTANGLE</code>.
	 */
	public final TableField<AdsenseRecord, String> ADSENSESLOTBIGRECTANGLE = createField("ADSENSESLOTBIGRECTANGLE", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ADSENSESLOTWIDESKYCRAPER</code>.
	 */
	public final TableField<AdsenseRecord, String> ADSENSESLOTWIDESKYCRAPER = createField("ADSENSESLOTWIDESKYCRAPER", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>BLOGSTACK.ADSENSE.ADSENSESLOTHORIZONTALSKYCRAPER</code>.
	 */
	public final TableField<AdsenseRecord, String> ADSENSESLOTHORIZONTALSKYCRAPER = createField("ADSENSESLOTHORIZONTALSKYCRAPER", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * Create a <code>BLOGSTACK.ADSENSE</code> table reference
	 */
	public Adsense() {
		this("ADSENSE", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.ADSENSE</code> table reference
	 */
	public Adsense(String alias) {
		this(alias, ADSENSE);
	}

	private Adsense(String alias, Table<AdsenseRecord> aliased) {
		this(alias, aliased, null);
	}

	private Adsense(String alias, Table<AdsenseRecord> aliased, Field<?>[] parameters) {
		super(alias, Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AdsenseRecord, Long> getIdentity() {
		return Keys.IDENTITY_ADSENSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AdsenseRecord> getPrimaryKey() {
		return Keys.PK_ADSENSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AdsenseRecord>> getKeys() {
		return Arrays.<UniqueKey<AdsenseRecord>>asList(Keys.PK_ADSENSE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Adsense as(String alias) {
		return new Adsense(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Adsense rename(String name) {
		return new Adsense(name, null);
	}
}
