/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;


import info.blogstack.persistence.jooq.Blogstack;
import info.blogstack.persistence.jooq.Keys;
import info.blogstack.persistence.jooq.tables.records.ImportSourceRecord;
import info.blogstack.persistence.records.DateTimeConverter;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImportSource extends TableImpl<ImportSourceRecord> {

	private static final long serialVersionUID = -1362254319;

	/**
	 * The reference instance of <code>BLOGSTACK.IMPORT_SOURCE</code>
	 */
	public static final ImportSource IMPORT_SOURCE = new ImportSource();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ImportSourceRecord> getRecordType() {
		return ImportSourceRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.IMPORT_SOURCE.ID</code>.
	 */
	public final TableField<ImportSourceRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.IMPORT_SOURCE.CREATIONDATE</code>.
	 */
	public final TableField<ImportSourceRecord, DateTime> CREATIONDATE = createField("CREATIONDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateTimeConverter());

	/**
	 * The column <code>BLOGSTACK.IMPORT_SOURCE.UPDATEDATE</code>.
	 */
	public final TableField<ImportSourceRecord, DateTime> UPDATEDATE = createField("UPDATEDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateTimeConverter());

	/**
	 * Create a <code>BLOGSTACK.IMPORT_SOURCE</code> table reference
	 */
	public ImportSource() {
		this("IMPORT_SOURCE", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.IMPORT_SOURCE</code> table reference
	 */
	public ImportSource(String alias) {
		this(alias, IMPORT_SOURCE);
	}

	private ImportSource(String alias, Table<ImportSourceRecord> aliased) {
		this(alias, aliased, null);
	}

	private ImportSource(String alias, Table<ImportSourceRecord> aliased, Field<?>[] parameters) {
		super(alias, Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ImportSourceRecord, Long> getIdentity() {
		return Keys.IDENTITY_IMPORT_SOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ImportSourceRecord> getPrimaryKey() {
		return Keys.PK_IMPORT_SOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ImportSourceRecord>> getKeys() {
		return Arrays.<UniqueKey<ImportSourceRecord>>asList(Keys.PK_IMPORT_SOURCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImportSource as(String alias) {
		return new ImportSource(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ImportSource rename(String name) {
		return new ImportSource(name, null);
	}
}
