/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexation extends org.jooq.impl.TableImpl<info.blogstack.persistence.jooq.tables.records.IndexationRecord> {

	private static final long serialVersionUID = 1609099255;

	/**
	 * The reference instance of <code>BLOGSTACK.INDEXATION</code>
	 */
	public static final info.blogstack.persistence.jooq.tables.Indexation INDEXATION = new info.blogstack.persistence.jooq.tables.Indexation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<info.blogstack.persistence.jooq.tables.records.IndexationRecord> getRecordType() {
		return info.blogstack.persistence.jooq.tables.records.IndexationRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.INDEXATION.ID</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.IndexationRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.INDEXATION.CREATIONDATE</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.IndexationRecord, org.joda.time.DateTime> CREATIONDATE = createField("CREATIONDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new info.blogstack.persistence.records.DateTimeConverter());

	/**
	 * Create a <code>BLOGSTACK.INDEXATION</code> table reference
	 */
	public Indexation() {
		this("INDEXATION", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.INDEXATION</code> table reference
	 */
	public Indexation(java.lang.String alias) {
		this(alias, info.blogstack.persistence.jooq.tables.Indexation.INDEXATION);
	}

	private Indexation(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.IndexationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Indexation(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.IndexationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, info.blogstack.persistence.jooq.Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<info.blogstack.persistence.jooq.tables.records.IndexationRecord, java.lang.Long> getIdentity() {
		return info.blogstack.persistence.jooq.Keys.IDENTITY_INDEXATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.IndexationRecord> getPrimaryKey() {
		return info.blogstack.persistence.jooq.Keys.PK_INDEXATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.IndexationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.IndexationRecord>>asList(info.blogstack.persistence.jooq.Keys.PK_INDEXATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public info.blogstack.persistence.jooq.tables.Indexation as(java.lang.String alias) {
		return new info.blogstack.persistence.jooq.tables.Indexation(alias, this);
	}

	/**
	 * Rename this table
	 */
	public info.blogstack.persistence.jooq.tables.Indexation rename(java.lang.String name) {
		return new info.blogstack.persistence.jooq.tables.Indexation(name, null);
	}
}
