/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;


import info.blogstack.persistence.jooq.Blogstack;
import info.blogstack.persistence.jooq.Keys;
import info.blogstack.persistence.jooq.tables.records.IndexationRecord;
import info.blogstack.persistence.records.DateTimeConverter;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexation extends TableImpl<IndexationRecord> {

	private static final long serialVersionUID = 311629541;

	/**
	 * The reference instance of <code>BLOGSTACK.INDEXATION</code>
	 */
	public static final Indexation INDEXATION = new Indexation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IndexationRecord> getRecordType() {
		return IndexationRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.INDEXATION.ID</code>.
	 */
	public final TableField<IndexationRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.INDEXATION.CREATIONDATE</code>.
	 */
	public final TableField<IndexationRecord, DateTime> CREATIONDATE = createField("CREATIONDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateTimeConverter());

	/**
	 * Create a <code>BLOGSTACK.INDEXATION</code> table reference
	 */
	public Indexation() {
		this("INDEXATION", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.INDEXATION</code> table reference
	 */
	public Indexation(String alias) {
		this(alias, INDEXATION);
	}

	private Indexation(String alias, Table<IndexationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Indexation(String alias, Table<IndexationRecord> aliased, Field<?>[] parameters) {
		super(alias, Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<IndexationRecord, Long> getIdentity() {
		return Keys.IDENTITY_INDEXATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IndexationRecord> getPrimaryKey() {
		return Keys.PK_INDEXATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IndexationRecord>> getKeys() {
		return Arrays.<UniqueKey<IndexationRecord>>asList(Keys.PK_INDEXATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Indexation as(String alias) {
		return new Indexation(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Indexation rename(String name) {
		return new Indexation(name, null);
	}
}
