/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Label extends org.jooq.impl.TableImpl<info.blogstack.persistence.jooq.tables.records.LabelRecord> {

	private static final long serialVersionUID = 1574365188;

	/**
	 * The reference instance of <code>BLOGSTACK.LABEL</code>
	 */
	public static final info.blogstack.persistence.jooq.tables.Label LABEL = new info.blogstack.persistence.jooq.tables.Label();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<info.blogstack.persistence.jooq.tables.records.LabelRecord> getRecordType() {
		return info.blogstack.persistence.jooq.tables.records.LabelRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.LABEL.ID</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.LabelRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.LABEL.CREATIONDATE</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.LabelRecord, org.joda.time.DateTime> CREATIONDATE = createField("CREATIONDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new info.blogstack.persistence.records.DateTimeConverter());

	/**
	 * The column <code>BLOGSTACK.LABEL.NAME</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.LabelRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>BLOGSTACK.LABEL.HASH</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.LabelRecord, java.lang.String> HASH = createField("HASH", org.jooq.impl.SQLDataType.VARCHAR.length(24), this, "");

	/**
	 * The column <code>BLOGSTACK.LABEL.ENABLED</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.LabelRecord, java.lang.Boolean> ENABLED = createField("ENABLED", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>BLOGSTACK.LABEL.VISIBLE</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.LabelRecord, java.lang.Boolean> VISIBLE = createField("VISIBLE", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>BLOGSTACK.LABEL</code> table reference
	 */
	public Label() {
		this("LABEL", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.LABEL</code> table reference
	 */
	public Label(java.lang.String alias) {
		this(alias, info.blogstack.persistence.jooq.tables.Label.LABEL);
	}

	private Label(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.LabelRecord> aliased) {
		this(alias, aliased, null);
	}

	private Label(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.LabelRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, info.blogstack.persistence.jooq.Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<info.blogstack.persistence.jooq.tables.records.LabelRecord, java.lang.Long> getIdentity() {
		return info.blogstack.persistence.jooq.Keys.IDENTITY_LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.LabelRecord> getPrimaryKey() {
		return info.blogstack.persistence.jooq.Keys.PK_LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.LabelRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.LabelRecord>>asList(info.blogstack.persistence.jooq.Keys.PK_LABEL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public info.blogstack.persistence.jooq.tables.Label as(java.lang.String alias) {
		return new info.blogstack.persistence.jooq.tables.Label(alias, this);
	}

	/**
	 * Rename this table
	 */
	public info.blogstack.persistence.jooq.tables.Label rename(java.lang.String name) {
		return new info.blogstack.persistence.jooq.tables.Label(name, null);
	}
}
