/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;


import info.blogstack.persistence.jooq.Blogstack;
import info.blogstack.persistence.jooq.Keys;
import info.blogstack.persistence.jooq.tables.records.LabelRecord;
import info.blogstack.persistence.records.DateTimeConverter;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Label extends TableImpl<LabelRecord> {

	private static final long serialVersionUID = 88065926;

	/**
	 * The reference instance of <code>BLOGSTACK.LABEL</code>
	 */
	public static final Label LABEL = new Label();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LabelRecord> getRecordType() {
		return LabelRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.LABEL.ID</code>.
	 */
	public final TableField<LabelRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.LABEL.CREATIONDATE</code>.
	 */
	public final TableField<LabelRecord, DateTime> CREATIONDATE = createField("CREATIONDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateTimeConverter());

	/**
	 * The column <code>BLOGSTACK.LABEL.NAME</code>.
	 */
	public final TableField<LabelRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>BLOGSTACK.LABEL.HASH</code>.
	 */
	public final TableField<LabelRecord, String> HASH = createField("HASH", org.jooq.impl.SQLDataType.VARCHAR.length(24), this, "");

	/**
	 * The column <code>BLOGSTACK.LABEL.ENABLED</code>.
	 */
	public final TableField<LabelRecord, Boolean> ENABLED = createField("ENABLED", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>BLOGSTACK.LABEL.VISIBLE</code>.
	 */
	public final TableField<LabelRecord, Boolean> VISIBLE = createField("VISIBLE", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>BLOGSTACK.LABEL</code> table reference
	 */
	public Label() {
		this("LABEL", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.LABEL</code> table reference
	 */
	public Label(String alias) {
		this(alias, LABEL);
	}

	private Label(String alias, Table<LabelRecord> aliased) {
		this(alias, aliased, null);
	}

	private Label(String alias, Table<LabelRecord> aliased, Field<?>[] parameters) {
		super(alias, Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<LabelRecord, Long> getIdentity() {
		return Keys.IDENTITY_LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<LabelRecord> getPrimaryKey() {
		return Keys.PK_LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<LabelRecord>> getKeys() {
		return Arrays.<UniqueKey<LabelRecord>>asList(Keys.PK_LABEL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Label as(String alias) {
		return new Label(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Label rename(String name) {
		return new Label(name, null);
	}
}
