/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newsletter extends org.jooq.impl.TableImpl<info.blogstack.persistence.jooq.tables.records.NewsletterRecord> {

	private static final long serialVersionUID = -1928307953;

	/**
	 * The reference instance of <code>BLOGSTACK.NEWSLETTER</code>
	 */
	public static final info.blogstack.persistence.jooq.tables.Newsletter NEWSLETTER = new info.blogstack.persistence.jooq.tables.Newsletter();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<info.blogstack.persistence.jooq.tables.records.NewsletterRecord> getRecordType() {
		return info.blogstack.persistence.jooq.tables.records.NewsletterRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.NEWSLETTER.ID</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.NewsletterRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.NEWSLETTER.CREATIONDATE</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.NewsletterRecord, org.joda.time.DateTime> CREATIONDATE = createField("CREATIONDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new info.blogstack.persistence.records.DateTimeConverter());

	/**
	 * Create a <code>BLOGSTACK.NEWSLETTER</code> table reference
	 */
	public Newsletter() {
		this("NEWSLETTER", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.NEWSLETTER</code> table reference
	 */
	public Newsletter(java.lang.String alias) {
		this(alias, info.blogstack.persistence.jooq.tables.Newsletter.NEWSLETTER);
	}

	private Newsletter(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.NewsletterRecord> aliased) {
		this(alias, aliased, null);
	}

	private Newsletter(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.NewsletterRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, info.blogstack.persistence.jooq.Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<info.blogstack.persistence.jooq.tables.records.NewsletterRecord, java.lang.Long> getIdentity() {
		return info.blogstack.persistence.jooq.Keys.IDENTITY_NEWSLETTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.NewsletterRecord> getPrimaryKey() {
		return info.blogstack.persistence.jooq.Keys.PK_NEWSLETTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.NewsletterRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.NewsletterRecord>>asList(info.blogstack.persistence.jooq.Keys.PK_NEWSLETTER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public info.blogstack.persistence.jooq.tables.Newsletter as(java.lang.String alias) {
		return new info.blogstack.persistence.jooq.tables.Newsletter(alias, this);
	}

	/**
	 * Rename this table
	 */
	public info.blogstack.persistence.jooq.tables.Newsletter rename(java.lang.String name) {
		return new info.blogstack.persistence.jooq.tables.Newsletter(name, null);
	}
}
