/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;


import info.blogstack.persistence.jooq.Blogstack;
import info.blogstack.persistence.jooq.Keys;
import info.blogstack.persistence.jooq.tables.records.NewsletterRecord;
import info.blogstack.persistence.records.DateTimeConverter;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Newsletter extends TableImpl<NewsletterRecord> {

	private static final long serialVersionUID = -1599337543;

	/**
	 * The reference instance of <code>BLOGSTACK.NEWSLETTER</code>
	 */
	public static final Newsletter NEWSLETTER = new Newsletter();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NewsletterRecord> getRecordType() {
		return NewsletterRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.NEWSLETTER.ID</code>.
	 */
	public final TableField<NewsletterRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.NEWSLETTER.CREATIONDATE</code>.
	 */
	public final TableField<NewsletterRecord, DateTime> CREATIONDATE = createField("CREATIONDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new DateTimeConverter());

	/**
	 * Create a <code>BLOGSTACK.NEWSLETTER</code> table reference
	 */
	public Newsletter() {
		this("NEWSLETTER", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.NEWSLETTER</code> table reference
	 */
	public Newsletter(String alias) {
		this(alias, NEWSLETTER);
	}

	private Newsletter(String alias, Table<NewsletterRecord> aliased) {
		this(alias, aliased, null);
	}

	private Newsletter(String alias, Table<NewsletterRecord> aliased, Field<?>[] parameters) {
		super(alias, Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<NewsletterRecord, Long> getIdentity() {
		return Keys.IDENTITY_NEWSLETTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<NewsletterRecord> getPrimaryKey() {
		return Keys.PK_NEWSLETTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<NewsletterRecord>> getKeys() {
		return Arrays.<UniqueKey<NewsletterRecord>>asList(Keys.PK_NEWSLETTER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Newsletter as(String alias) {
		return new Newsletter(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Newsletter rename(String name) {
		return new Newsletter(name, null);
	}
}
