/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;


import info.blogstack.persistence.jooq.Blogstack;
import info.blogstack.persistence.jooq.Keys;
import info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostsLabels extends TableImpl<PostsLabelsRecord> {

	private static final long serialVersionUID = -1375324080;

	/**
	 * The reference instance of <code>BLOGSTACK.POSTS_LABELS</code>
	 */
	public static final PostsLabels POSTS_LABELS = new PostsLabels();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PostsLabelsRecord> getRecordType() {
		return PostsLabelsRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.POSTS_LABELS.ID</code>.
	 */
	public final TableField<PostsLabelsRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.POSTS_LABELS.POST_ID</code>.
	 */
	public final TableField<PostsLabelsRecord, Long> POST_ID = createField("POST_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>BLOGSTACK.POSTS_LABELS.LABEL_ID</code>.
	 */
	public final TableField<PostsLabelsRecord, Long> LABEL_ID = createField("LABEL_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>BLOGSTACK.POSTS_LABELS</code> table reference
	 */
	public PostsLabels() {
		this("POSTS_LABELS", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.POSTS_LABELS</code> table reference
	 */
	public PostsLabels(String alias) {
		this(alias, POSTS_LABELS);
	}

	private PostsLabels(String alias, Table<PostsLabelsRecord> aliased) {
		this(alias, aliased, null);
	}

	private PostsLabels(String alias, Table<PostsLabelsRecord> aliased, Field<?>[] parameters) {
		super(alias, Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PostsLabelsRecord, Long> getIdentity() {
		return Keys.IDENTITY_POSTS_LABELS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PostsLabelsRecord> getPrimaryKey() {
		return Keys.PK_POSTS_LABELS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PostsLabelsRecord>> getKeys() {
		return Arrays.<UniqueKey<PostsLabelsRecord>>asList(Keys.PK_POSTS_LABELS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<PostsLabelsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<PostsLabelsRecord, ?>>asList(Keys.POSTS_LABELS_POST_ID, Keys.POSTS_LABELS_LABEL_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostsLabels as(String alias) {
		return new PostsLabels(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PostsLabels rename(String name) {
		return new PostsLabels(name, null);
	}
}
