/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostsLabels extends org.jooq.impl.TableImpl<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord> {

	private static final long serialVersionUID = -770730704;

	/**
	 * The reference instance of <code>BLOGSTACK.POSTS_LABELS</code>
	 */
	public static final info.blogstack.persistence.jooq.tables.PostsLabels POSTS_LABELS = new info.blogstack.persistence.jooq.tables.PostsLabels();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord> getRecordType() {
		return info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord.class;
	}

	/**
	 * The column <code>BLOGSTACK.POSTS_LABELS.ID</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>BLOGSTACK.POSTS_LABELS.POST_ID</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord, java.lang.Long> POST_ID = createField("POST_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>BLOGSTACK.POSTS_LABELS.LABEL_ID</code>.
	 */
	public final org.jooq.TableField<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord, java.lang.Long> LABEL_ID = createField("LABEL_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>BLOGSTACK.POSTS_LABELS</code> table reference
	 */
	public PostsLabels() {
		this("POSTS_LABELS", null);
	}

	/**
	 * Create an aliased <code>BLOGSTACK.POSTS_LABELS</code> table reference
	 */
	public PostsLabels(java.lang.String alias) {
		this(alias, info.blogstack.persistence.jooq.tables.PostsLabels.POSTS_LABELS);
	}

	private PostsLabels(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord> aliased) {
		this(alias, aliased, null);
	}

	private PostsLabels(java.lang.String alias, org.jooq.Table<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, info.blogstack.persistence.jooq.Blogstack.BLOGSTACK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord, java.lang.Long> getIdentity() {
		return info.blogstack.persistence.jooq.Keys.IDENTITY_POSTS_LABELS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord> getPrimaryKey() {
		return info.blogstack.persistence.jooq.Keys.PK_POSTS_LABELS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord>>asList(info.blogstack.persistence.jooq.Keys.PK_POSTS_LABELS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<info.blogstack.persistence.jooq.tables.records.PostsLabelsRecord, ?>>asList(info.blogstack.persistence.jooq.Keys.POSTS_LABELS_POST_ID, info.blogstack.persistence.jooq.Keys.POSTS_LABELS_LABEL_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public info.blogstack.persistence.jooq.tables.PostsLabels as(java.lang.String alias) {
		return new info.blogstack.persistence.jooq.tables.PostsLabels(alias, this);
	}

	/**
	 * Rename this table
	 */
	public info.blogstack.persistence.jooq.tables.PostsLabels rename(java.lang.String name) {
		return new info.blogstack.persistence.jooq.tables.PostsLabels(name, null);
	}
}
