/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq;


import info.blogstack.persistence.jooq.tables.Adsense;
import info.blogstack.persistence.jooq.tables.ImportSource;
import info.blogstack.persistence.jooq.tables.Indexation;
import info.blogstack.persistence.jooq.tables.Label;
import info.blogstack.persistence.jooq.tables.Newsletter;
import info.blogstack.persistence.jooq.tables.Post;
import info.blogstack.persistence.jooq.tables.PostsIndexations;
import info.blogstack.persistence.jooq.tables.PostsLabels;
import info.blogstack.persistence.jooq.tables.Source;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blogstack extends SchemaImpl {

	private static final long serialVersionUID = 673704667;

	/**
	 * The reference instance of <code>BLOGSTACK</code>
	 */
	public static final Blogstack BLOGSTACK = new Blogstack();

	/**
	 * No further instances allowed
	 */
	private Blogstack() {
		super("BLOGSTACK");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.SYSTEM_SEQUENCE_2E02FFE3_8701_48C3_81FE_341F2CC2BF06,
			Sequences.SYSTEM_SEQUENCE_39562988_6D23_4305_B39C_27DBA18DB8DE,
			Sequences.SYSTEM_SEQUENCE_8CD3AFD5_2A41_4A0E_8369_E4F6CCA4D07D,
			Sequences.SYSTEM_SEQUENCE_9C8E7D15_5525_4D62_8CAD_84D8646A6A56,
			Sequences.SYSTEM_SEQUENCE_A7C74032_E4F0_43CD_99DB_E135DA5DAFA1,
			Sequences.SYSTEM_SEQUENCE_A8FC292C_948E_4DBF_B050_6B6905BDA5E8,
			Sequences.SYSTEM_SEQUENCE_AAC90520_24FC_45CF_B7F2_BBA672F82CC1,
			Sequences.SYSTEM_SEQUENCE_C958AC1C_6F7A_4310_8564_E5406FB1FFD2,
			Sequences.SYSTEM_SEQUENCE_E696ABD2_9724_469F_9EF9_59427C97B083);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Indexation.INDEXATION,
			Adsense.ADSENSE,
			ImportSource.IMPORT_SOURCE,
			Newsletter.NEWSLETTER,
			Post.POST,
			Label.LABEL,
			PostsIndexations.POSTS_INDEXATIONS,
			PostsLabels.POSTS_LABELS,
			Source.SOURCE);
	}
}
