/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in BLOGSTACK
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_2E02FFE3_8701_48C3_81FE_341F2CC2BF06</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_2E02FFE3_8701_48C3_81FE_341F2CC2BF06 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2E02FFE3_8701_48C3_81FE_341F2CC2BF06", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_39562988_6D23_4305_B39C_27DBA18DB8DE</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_39562988_6D23_4305_B39C_27DBA18DB8DE = new SequenceImpl<Long>("SYSTEM_SEQUENCE_39562988_6D23_4305_B39C_27DBA18DB8DE", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_8CD3AFD5_2A41_4A0E_8369_E4F6CCA4D07D</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_8CD3AFD5_2A41_4A0E_8369_E4F6CCA4D07D = new SequenceImpl<Long>("SYSTEM_SEQUENCE_8CD3AFD5_2A41_4A0E_8369_E4F6CCA4D07D", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_9C8E7D15_5525_4D62_8CAD_84D8646A6A56</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_9C8E7D15_5525_4D62_8CAD_84D8646A6A56 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_9C8E7D15_5525_4D62_8CAD_84D8646A6A56", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_A7C74032_E4F0_43CD_99DB_E135DA5DAFA1</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_A7C74032_E4F0_43CD_99DB_E135DA5DAFA1 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_A7C74032_E4F0_43CD_99DB_E135DA5DAFA1", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_A8FC292C_948E_4DBF_B050_6B6905BDA5E8</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_A8FC292C_948E_4DBF_B050_6B6905BDA5E8 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_A8FC292C_948E_4DBF_B050_6B6905BDA5E8", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_AAC90520_24FC_45CF_B7F2_BBA672F82CC1</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_AAC90520_24FC_45CF_B7F2_BBA672F82CC1 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_AAC90520_24FC_45CF_B7F2_BBA672F82CC1", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_C958AC1C_6F7A_4310_8564_E5406FB1FFD2</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_C958AC1C_6F7A_4310_8564_E5406FB1FFD2 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_C958AC1C_6F7A_4310_8564_E5406FB1FFD2", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>BLOGSTACK.SYSTEM_SEQUENCE_E696ABD2_9724_469F_9EF9_59427C97B083</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_E696ABD2_9724_469F_9EF9_59427C97B083 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_E696ABD2_9724_469F_9EF9_59427C97B083", Blogstack.BLOGSTACK, org.jooq.impl.SQLDataType.BIGINT);
}
