/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq;

/**
 * Convenience access to all tables in BLOGSTACK
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table BLOGSTACK.INDEXATION
	 */
	public static final info.blogstack.persistence.jooq.tables.Indexation INDEXATION = info.blogstack.persistence.jooq.tables.Indexation.INDEXATION;

	/**
	 * The table BLOGSTACK.ADSENSE
	 */
	public static final info.blogstack.persistence.jooq.tables.Adsense ADSENSE = info.blogstack.persistence.jooq.tables.Adsense.ADSENSE;

	/**
	 * The table BLOGSTACK.IMPORT_SOURCE
	 */
	public static final info.blogstack.persistence.jooq.tables.ImportSource IMPORT_SOURCE = info.blogstack.persistence.jooq.tables.ImportSource.IMPORT_SOURCE;

	/**
	 * The table BLOGSTACK.NEWSLETTER
	 */
	public static final info.blogstack.persistence.jooq.tables.Newsletter NEWSLETTER = info.blogstack.persistence.jooq.tables.Newsletter.NEWSLETTER;

	/**
	 * The table BLOGSTACK.POST
	 */
	public static final info.blogstack.persistence.jooq.tables.Post POST = info.blogstack.persistence.jooq.tables.Post.POST;

	/**
	 * The table BLOGSTACK.LABEL
	 */
	public static final info.blogstack.persistence.jooq.tables.Label LABEL = info.blogstack.persistence.jooq.tables.Label.LABEL;

	/**
	 * The table BLOGSTACK.POSTS_INDEXATIONS
	 */
	public static final info.blogstack.persistence.jooq.tables.PostsIndexations POSTS_INDEXATIONS = info.blogstack.persistence.jooq.tables.PostsIndexations.POSTS_INDEXATIONS;

	/**
	 * The table BLOGSTACK.POSTS_LABELS
	 */
	public static final info.blogstack.persistence.jooq.tables.PostsLabels POSTS_LABELS = info.blogstack.persistence.jooq.tables.PostsLabels.POSTS_LABELS;

	/**
	 * The table BLOGSTACK.SOURCE
	 */
	public static final info.blogstack.persistence.jooq.tables.Source SOURCE = info.blogstack.persistence.jooq.tables.Source.SOURCE;
}
