/**
 * This class is generated by jOOQ
 */
package info.blogstack.persistence.jooq;


import info.blogstack.persistence.jooq.tables.Adsense;
import info.blogstack.persistence.jooq.tables.ImportSource;
import info.blogstack.persistence.jooq.tables.Indexation;
import info.blogstack.persistence.jooq.tables.Label;
import info.blogstack.persistence.jooq.tables.Newsletter;
import info.blogstack.persistence.jooq.tables.Post;
import info.blogstack.persistence.jooq.tables.PostsIndexations;
import info.blogstack.persistence.jooq.tables.PostsLabels;
import info.blogstack.persistence.jooq.tables.Source;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in BLOGSTACK
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table BLOGSTACK.INDEXATION
	 */
	public static final Indexation INDEXATION = info.blogstack.persistence.jooq.tables.Indexation.INDEXATION;

	/**
	 * The table BLOGSTACK.ADSENSE
	 */
	public static final Adsense ADSENSE = info.blogstack.persistence.jooq.tables.Adsense.ADSENSE;

	/**
	 * The table BLOGSTACK.IMPORT_SOURCE
	 */
	public static final ImportSource IMPORT_SOURCE = info.blogstack.persistence.jooq.tables.ImportSource.IMPORT_SOURCE;

	/**
	 * The table BLOGSTACK.NEWSLETTER
	 */
	public static final Newsletter NEWSLETTER = info.blogstack.persistence.jooq.tables.Newsletter.NEWSLETTER;

	/**
	 * The table BLOGSTACK.POST
	 */
	public static final Post POST = info.blogstack.persistence.jooq.tables.Post.POST;

	/**
	 * The table BLOGSTACK.LABEL
	 */
	public static final Label LABEL = info.blogstack.persistence.jooq.tables.Label.LABEL;

	/**
	 * The table BLOGSTACK.POSTS_INDEXATIONS
	 */
	public static final PostsIndexations POSTS_INDEXATIONS = info.blogstack.persistence.jooq.tables.PostsIndexations.POSTS_INDEXATIONS;

	/**
	 * The table BLOGSTACK.POSTS_LABELS
	 */
	public static final PostsLabels POSTS_LABELS = info.blogstack.persistence.jooq.tables.PostsLabels.POSTS_LABELS;

	/**
	 * The table BLOGSTACK.SOURCE
	 */
	public static final Source SOURCE = info.blogstack.persistence.jooq.tables.Source.SOURCE;
}
